name: 🚀 Release
on:
  push:
    branches:
      - main
  pull_request: {}
permissions:
  actions: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 🧪 Test
    strategy:
      matrix:
        version: [12, 14, 16, 18]
        include:
          - version: 18
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🃏 Run jest
        run: npm test -- --coverage=${{ matrix.coverage }}

      - uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}

  publish:
    name: 🚀 Publish
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
